---
name: Copilot Setup Steps for Integration Tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'all'
        type: choice
        options:
          - 'all'
          - 'integration_tests'
          - 'runtime'
          - 'e2e'

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: Verify Poetry installation
        run: |
          echo "Poetry version: $(poetry --version)"
          echo "Poetry location: $(which poetry)"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tmux libgtk-3-0 libnotify4 libnss3 \
            libxss1 libxtst6 xauth xvfb libgbm1 libasound2t64 netcat-openbsd

      - name: Install Python dependencies using Poetry
        run: |
          poetry install --with dev,test,runtime,evaluation

      - name: Build Environment
        run: make build
