name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: Setup Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Verify Poetry installation
        run: |
          echo "Poetry version: $(poetry --version)"
          echo "Poetry location: $(which poetry)"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tmux libgtk-3-0 libnotify4 libnss3 \
            libxss1 libxtst6 xauth xvfb libgbm1 libasound2t64 netcat-openbsd

      - name: Install Python dependencies using Poetry
        run: |
          poetry install --with dev,test,runtime,evaluation
